version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: discord_bot
    restart: always
    volumes:
      - ./src:/app
      - ./.env:/app/.env
